#!/usr/bin/env python3
"""Generate NorthAmerica_database_1.xlsx matching Pilots4U column structure."""
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment
from pathlib import Path

FACILITIES = [
    # ── CDMOs / CMOs ────────────────────────────────────────────────────────
    {
        "ID": 1001,
        "Facility": "Lonza Biologics Portsmouth",
        "Membership tier": "",
        "City": "Portsmouth",
        "Country": "United States",
        "Address": "101 International Drive, Portsmouth, NH 03801",
        "Contact person": "",
        "Website": "https://www.lonza.com",
        "Social links": "",
        "About": "Lonza's Portsmouth site is one of the world's largest single-use biomanufacturing facilities. The site operates mammalian cell culture manufacturing at commercial scale, including multi-tonne capacity in disposable bioreactors. It serves as a major hub for biologic drug substance production for global pharma and biotech customers.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "Fed-batch bioreactors\nPerfusion bioreactors\nChromatography purification\nUltrafiltration / diafiltration",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "Project management\nRegulatory support\nTech transfer",
        "Open 24/7": "Yes",
        "Extra information": "Capacity: multiple 20,000 L single-use bioreactors; expanded in 2021.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 1002,
        "Facility": "Lonza Biologics Vacaville",
        "Membership tier": "",
        "City": "Vacaville",
        "Country": "United States",
        "Address": "4000 Nelson Road, Vacaville, CA 95688",
        "Contact person": "",
        "Website": "https://www.lonza.com",
        "Social links": "",
        "About": "Lonza Vacaville is a large-scale stainless-steel mammalian cell culture manufacturing site, originally built by Genentech. Now owned by Lonza, it provides commercial biologic drug substance manufacturing services including cell culture fermentation and downstream processing for CDMO customers.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "Fed-batch stirred-tank bioreactors\nProtein A chromatography\nVirus filtration\nUF/DF",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "Tech transfer\nAnalytical services",
        "Open 24/7": "Yes",
        "Extra information": "Stainless-steel bioreactors up to 25,000 L.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 1003,
        "Facility": "Lonza Biologics Pearland",
        "Membership tier": "",
        "City": "Pearland",
        "Country": "United States",
        "Address": "2905 Lonza Drive, Pearland, TX 77584",
        "Contact person": "",
        "Website": "https://www.lonza.com",
        "Social links": "",
        "About": "Lonza's Pearland, Texas facility focuses on mammalian cell culture CDMO services with single-use bioreactor technology. The site supports clinical and commercial manufacturing for biopharmaceutical customers.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "Single-use bioreactors\nDownstream processing\nFill-finish",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "Tech transfer\nRegulatory support",
        "Open 24/7": "Yes",
        "Extra information": "",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 1004,
        "Facility": "Fujifilm Diosynth Biotechnologies RTP",
        "Membership tier": "",
        "City": "Research Triangle Park",
        "Country": "United States",
        "Address": "6051 George Watts Hill Drive, Research Triangle Park, NC 27709",
        "Contact person": "",
        "Website": "https://www.fujifilmdiosynth.com",
        "Social links": "",
        "About": "Fujifilm Diosynth Biotechnologies (formerly SAFC/Diosynth) in RTP is a leading CDMO offering microbial fermentation and mammalian cell culture services for clinical and commercial biologics. The site has deep expertise in recombinant proteins, including E. coli and yeast fermentation.",
        "Technology areas": "Mammalian cell culture\nMicrobial fermentation",
        "Technologies": "E. coli fermentation\nYeast fermentation\nMammalian cell culture\nProtein refolding\nChromatography purification",
        "No. of technologies": 5,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "Analytical development\nFormulation development\nTech transfer",
        "Open 24/7": "Yes",
        "Extra information": "Fermentation capacity up to 15,000 L; major site for biosimilar and biologic manufacturing.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 1005,
        "Facility": "Fujifilm Diosynth Biotechnologies College Station",
        "Membership tier": "",
        "City": "College Station",
        "Country": "United States",
        "Address": "1 Fujifilm Way, College Station, TX 77845",
        "Contact person": "",
        "Website": "https://www.fujifilmdiosynth.com",
        "Social links": "",
        "About": "Fujifilm Diosynth Biotechnologies' College Station site (formerly Kalon Biotherapeutics) specialises in large-scale mammalian cell culture CDMO services. The site supports commercial production of monoclonal antibodies and other biologic drugs.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "Large-scale bioreactors (up to 20,000 L)\nDownstream processing\nFill-finish",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "Regulatory support\nTech transfer",
        "Open 24/7": "Yes",
        "Extra information": "One of the largest CDMO sites in Texas; acquired by Fujifilm in 2011.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 1006,
        "Facility": "Catalent Biologics Bloomington",
        "Membership tier": "",
        "City": "Bloomington",
        "Country": "United States",
        "Address": "1500 Catalent Drive, Bloomington, IN 47404",
        "Contact person": "",
        "Website": "https://www.catalent.com",
        "Social links": "",
        "About": "Catalent's Bloomington biologics site offers large-scale mammalian cell culture manufacturing combined with fill-finish capabilities. The site is known for its GPEx technology for stable cell line development and high-yielding production of monoclonal antibodies and fusion proteins.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "GPEx cell line development\nFed-batch bioreactors (up to 2,000 L)\nFill-finish (vials, syringes)",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "Cell line development\nAnalytical services\nRegulatory support",
        "Open 24/7": "Yes",
        "Extra information": "Acquired by Novo Holdings in 2024 and rebranded as Novo Nordisk Manufacturing.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 1007,
        "Facility": "Catalent Biologics Madison",
        "Membership tier": "",
        "City": "Madison",
        "Country": "United States",
        "Address": "726 Heartland Trail, Madison, WI 53717",
        "Contact person": "",
        "Website": "https://www.catalent.com",
        "Social links": "",
        "About": "Catalent Madison offers viral vector CDMO services for gene therapy programs, including adeno-associated virus (AAV) and lentiviral vector manufacturing at clinical and commercial scales. The site also supports mRNA and lipid nanoparticle (LNP) manufacturing.",
        "Technology areas": "Viral vector\nmRNA\nLipid nanoparticle",
        "Technologies": "AAV manufacturing\nLentiviral vector production\nmRNA synthesis\nLNP formulation\nFill-finish",
        "No. of technologies": 5,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "Vector development\nAnalytical services",
        "Open 24/7": "Yes",
        "Extra information": "Former MaSTherCell site; major US hub for viral vector gene therapy manufacturing.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 1008,
        "Facility": "AGC Biologics Boulder",
        "Membership tier": "",
        "City": "Boulder",
        "Country": "United States",
        "Address": "5480 Airport Blvd, Boulder, CO 80301",
        "Contact person": "",
        "Website": "https://www.agcbbiologics.com",
        "Social links": "",
        "About": "AGC Biologics Boulder (formerly CMC Biologics) provides mammalian cell culture CDMO services at clinical and commercial scales. The site specialises in monoclonal antibody production and recombinant protein manufacturing with single-use and stainless-steel bioreactor systems.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "CHO cell culture\nSingle-use bioreactors\nStainless-steel bioreactors\nChromatographic purification",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "Cell line development\nAnalytical development\nRegulatory support",
        "Open 24/7": "Yes",
        "Extra information": "",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 1009,
        "Facility": "AGC Biologics Seattle",
        "Membership tier": "",
        "City": "Seattle",
        "Country": "United States",
        "Address": "10801 N Northup Way, Bothell, WA 98011",
        "Contact person": "",
        "Website": "https://www.agcbologics.com",
        "Social links": "",
        "About": "AGC Biologics' Seattle-area (Bothell, WA) site offers mammalian cell culture and microbial fermentation CDMO capabilities. The facility supports both clinical and commercial manufacturing of biologics.",
        "Technology areas": "Mammalian cell culture\nMicrobial fermentation",
        "Technologies": "CHO cell culture\nE. coli fermentation\nSingle-use bioreactors\nDownstream processing",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "Process development\nAnalytical services",
        "Open 24/7": "Yes",
        "Extra information": "",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 1010,
        "Facility": "KBI Biopharma Durham",
        "Membership tier": "",
        "City": "Durham",
        "Country": "United States",
        "Address": "4112 Hamlin Road, Durham, NC 27704",
        "Contact person": "",
        "Website": "https://www.kbibiopharma.com",
        "Social links": "",
        "About": "KBI Biopharma (formerly Laureate Biopharmaceutical Services) in Durham is a full-service CDMO offering mammalian cell culture and microbial fermentation manufacturing for clinical and commercial programs. The site has extensive experience with mAbs, fusion proteins, and recombinant enzymes.",
        "Technology areas": "Mammalian cell culture\nMicrobial fermentation",
        "Technologies": "Fed-batch CHO culture\nE. coli fermentation\nProtein purification\nFill-finish",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "Cell line development\nFormulation\nStability testing",
        "Open 24/7": "Yes",
        "Extra information": "Part of JSR Corporation (since 2021).",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 1011,
        "Facility": "WuXi Biologics Cranbury",
        "Membership tier": "",
        "City": "Cranbury",
        "Country": "United States",
        "Address": "158 Route 130 South, Cranbury, NJ 08512",
        "Contact person": "",
        "Website": "https://www.wuxibiologics.com",
        "Social links": "",
        "About": "WuXi Biologics' US site in Cranbury, New Jersey provides integrated CDMO services for biologic drug development and manufacturing, including cell line development, process development, and clinical-stage production of mammalian cell culture-derived biologics.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "CHO cell line development\nSingle-use bioreactors\nDownstream purification",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "Analytical development\nRegulatory filing support",
        "Open 24/7": "Yes",
        "Extra information": "",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 1012,
        "Facility": "Emergent BioSolutions Baltimore",
        "Membership tier": "",
        "City": "Baltimore",
        "Country": "United States",
        "Address": "5901 E. Lombard Street, Baltimore, MD 21224",
        "Contact person": "",
        "Website": "https://www.emergentbiosolutions.com",
        "Social links": "",
        "About": "Emergent BioSolutions' Baltimore manufacturing site is focused on large-scale biological manufacturing for government stockpile and commercial customers. The site produces anthrax vaccines, antitoxins, and has supported COVID-19 vaccine manufacturing (AstraZeneca, J&J).",
        "Technology areas": "Mammalian cell culture\nMicrobial fermentation",
        "Technologies": "Large-scale bioreactors\nMicrobial fermentation\nDownstream processing\nFill-finish",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "Government contract manufacturing\nSurge manufacturing",
        "Open 24/7": "Yes",
        "Extra information": "Temporary FDA suspension in 2021 following contamination incident during COVID vaccine production.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 1013,
        "Facility": "Recipharm Durham",
        "Membership tier": "",
        "City": "Durham",
        "Country": "United States",
        "Address": "4709 Creekstone Drive, Durham, NC 27703",
        "Contact person": "",
        "Website": "https://www.recipharm.com",
        "Social links": "",
        "About": "Recipharm Durham (formerly Cobra Biologics US) is a biologics CDMO offering mammalian and microbial manufacturing services. The site specialises in clinical-stage production and has capabilities for viral vector manufacturing.",
        "Technology areas": "Mammalian cell culture\nViral vector\nMicrobial fermentation",
        "Technologies": "CHO cell culture\nAAV production\nE. coli fermentation",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "Process development\nAnalytical services",
        "Open 24/7": "Yes",
        "Extra information": "",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 1014,
        "Facility": "National Resilience Durham",
        "Membership tier": "",
        "City": "Durham",
        "Country": "United States",
        "Address": "4800 Meadow Wood Lane, Chantilly, VA 20151",
        "Contact person": "",
        "Website": "https://www.resilience.com",
        "Social links": "",
        "About": "National Resilience is a CDMO with multiple North American sites. The company focuses on advanced manufacturing of biologics, gene therapies, and complex drug products, emphasising resilient domestic biomanufacturing capacity.",
        "Technology areas": "Mammalian cell culture\nViral vector\nmRNA",
        "Technologies": "CHO cell culture\nAAV manufacturing\nmRNA synthesis\nLNP formulation\nFill-finish",
        "No. of technologies": 5,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "Process development\nRegulatory strategy",
        "Open 24/7": "Yes",
        "Extra information": "Multiple NA sites including San Diego CA, Mississauga ON (Canada), Alachua FL; founded 2020 with >$2B investment.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 1015,
        "Facility": "Cytovance Biologics Oklahoma City",
        "Membership tier": "",
        "City": "Oklahoma City",
        "Country": "United States",
        "Address": "655 Research Pkwy #400, Oklahoma City, OK 73104",
        "Contact person": "",
        "Website": "https://www.cytovance.com",
        "Social links": "",
        "About": "Cytovance Biologics is a full-service biologics CDMO offering both mammalian cell culture and microbial fermentation manufacturing. The site supports early-phase clinical programs and has capabilities for mAbs, recombinant proteins, and plasmid DNA production.",
        "Technology areas": "Mammalian cell culture\nMicrobial fermentation",
        "Technologies": "CHO and HEK293 cell culture\nE. coli and yeast fermentation\nPlasmid DNA manufacturing\nProtein purification",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "Cell line development\nAnalytical development",
        "Open 24/7": "Yes",
        "Extra information": "",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    # ── Captive pharma/biotech ───────────────────────────────────────────────
    {
        "ID": 2001,
        "Facility": "Genentech Vacaville",
        "Membership tier": "",
        "City": "Vacaville",
        "Country": "United States",
        "Address": "1 DNA Way, Vacaville, CA 95688",
        "Contact person": "",
        "Website": "https://www.gene.com",
        "Social links": "",
        "About": "Genentech's Vacaville manufacturing site is one of the largest mammalian cell culture biomanufacturing facilities in the world. The site produces commercial biologics for Roche/Genentech including Avastin, Herceptin, and Rituxan, using large-scale stainless-steel bioreactors.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "Large-scale CHO bioreactors (up to 25,000 L)\nDownstream purification\nFill-finish",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "Captive Roche/Genentech site; one of the highest-capacity bioprocessing sites globally.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 2002,
        "Facility": "Genentech Oceanside",
        "Membership tier": "",
        "City": "Oceanside",
        "Country": "United States",
        "Address": "4300 Sylvia Lane, Oceanside, CA 92056",
        "Contact person": "",
        "Website": "https://www.gene.com",
        "Social links": "",
        "About": "Genentech's Oceanside facility is a large-scale mammalian cell culture manufacturing site focused on production of commercial biologic drugs. The site also handles fill-finish and packaging operations.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "CHO cell culture\nFill-finish\nPackaging",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "Opened in 2009; part of the Roche global network.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 2003,
        "Facility": "Amgen Thousand Oaks",
        "Membership tier": "",
        "City": "Thousand Oaks",
        "Country": "United States",
        "Address": "1 Amgen Center Drive, Thousand Oaks, CA 91320",
        "Contact person": "",
        "Website": "https://www.amgen.com",
        "Social links": "",
        "About": "Amgen's Thousand Oaks headquarters includes its first and largest biomanufacturing campus. The site produces commercial biologics including Enbrel, Neupogen, and Prolia, using large-scale CHO mammalian cell culture. The campus also houses significant process development and pilot manufacturing facilities.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "Large-scale CHO bioreactors\nPilot-scale bioreactors\nDownstream purification\nFill-finish",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "Founding site of Amgen; one of the historic centres of US biomanufacturing.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 2004,
        "Facility": "Amgen West Greenwich",
        "Membership tier": "",
        "City": "West Greenwich",
        "Country": "United States",
        "Address": "40 Technology Way, West Greenwich, RI 02817",
        "Contact person": "",
        "Website": "https://www.amgen.com",
        "Social links": "",
        "About": "Amgen Rhode Island is a large commercial biomanufacturing site producing biologics including Enbrel. The facility uses mammalian cell culture technology with large-scale bioreactors and comprehensive downstream processing.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "Large-scale CHO bioreactors (up to 15,000 L)\nDownstream processing\nFill-finish",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 2005,
        "Facility": "Bristol Myers Squibb Devens",
        "Membership tier": "",
        "City": "Devens",
        "Country": "United States",
        "Address": "100 Binney Street, Devens, MA 01434",
        "Contact person": "",
        "Website": "https://www.bms.com",
        "Social links": "",
        "About": "Bristol Myers Squibb's Devens biomanufacturing site is a state-of-the-art large-scale mammalian cell culture facility producing commercial biologics. The site uses single-use bioreactor technology and is one of BMS's newest and most advanced manufacturing plants.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "Single-use stirred-tank bioreactors\nChromatographic purification\nVirus inactivation/filtration\nFill-finish",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "Opened 2019; 90,000 sq ft; produces Opdivo, Eliquis intermediates.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 2006,
        "Facility": "Regeneron Rensselaer",
        "Membership tier": "",
        "City": "Rensselaer",
        "Country": "United States",
        "Address": "1 Regeneron Way, Rensselaer, NY 12144",
        "Contact person": "",
        "Website": "https://www.regeneron.com",
        "Social links": "",
        "About": "Regeneron's Rensselaer campus is the company's primary biomanufacturing site for commercial production of its biologics portfolio including Eylea, Dupixent, Kevzara, and COVID-19 antibody therapies. The campus features large-scale mammalian cell culture manufacturing and fill-finish capabilities.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "Large-scale CHO bioreactors\nDownstream purification\nFill-finish\nPre-filled syringe assembly",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "One of the most productive commercial biologic manufacturing sites in the US; capacity expansions ongoing.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 2007,
        "Facility": "Biogen Research Triangle Park",
        "Membership tier": "",
        "City": "Research Triangle Park",
        "Country": "United States",
        "Address": "5000 Davis Drive, Research Triangle Park, NC 27709",
        "Contact person": "",
        "Website": "https://www.biogen.com",
        "Social links": "",
        "About": "Biogen's RTP facility is a large-scale mammalian cell culture manufacturing site for commercial biologics including multiple sclerosis drugs and spinal muscular atrophy therapy Spinraza. The site has been a major production hub since the 1990s.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "Large-scale CHO bioreactors (up to 15,000 L)\nDownstream processing\nFill-finish",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 2008,
        "Facility": "AbbVie Worcester",
        "Membership tier": "",
        "City": "Worcester",
        "Country": "United States",
        "Address": "100 Research Drive, Worcester, MA 01605",
        "Contact person": "",
        "Website": "https://www.abbvie.com",
        "Social links": "",
        "About": "AbbVie's Worcester site (formerly Pharmacyclics/ImmunoGen) is a biologics manufacturing facility focused on antibody-drug conjugate (ADC) production and mammalian cell culture. The site supports commercial production of oncology biologics.",
        "Technology areas": "Mammalian cell culture\nADC",
        "Technologies": "CHO cell culture\nADC conjugation\nDownstream purification",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 2009,
        "Facility": "Pfizer Andover",
        "Membership tier": "",
        "City": "Andover",
        "Country": "United States",
        "Address": "700 Chesterfield Pkwy West, Andover, MA 01810",
        "Contact person": "",
        "Website": "https://www.pfizer.com",
        "Social links": "",
        "About": "Pfizer's Andover site is one of the company's key US biomanufacturing facilities, producing commercial biologics including biosimilars and novel biologic drugs via mammalian cell culture. The site hosts significant process development and scale-up activities.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "Fed-batch CHO bioreactors\nChromatographic purification\nFill-finish",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "Site previously associated with former Wyeth biologics division.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 2010,
        "Facility": "Pfizer McPherson",
        "Membership tier": "",
        "City": "McPherson",
        "Country": "United States",
        "Address": "1000 Pfizer Road, McPherson, KS 67460",
        "Contact person": "",
        "Website": "https://www.pfizer.com",
        "Social links": "",
        "About": "Pfizer McPherson is a large sterile manufacturing and fill-finish facility that also handles biologics production. The site played a key role in COVID-19 vaccine manufacturing and supports commercial biologics including BioNTech mRNA COVID vaccine fill-finish.",
        "Technology areas": "Mammalian cell culture\nmRNA",
        "Technologies": "mRNA fill-finish\nSterile vial filling\nFreeze-drying",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "One of the world's largest COVID-19 vaccine fill-finish sites.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 2011,
        "Facility": "Sanofi Framingham",
        "Membership tier": "",
        "City": "Framingham",
        "Country": "United States",
        "Address": "49 New York Avenue, Framingham, MA 01701",
        "Contact person": "",
        "Website": "https://www.sanofi.com",
        "Social links": "",
        "About": "Sanofi's Framingham site is a significant biomanufacturing campus for mammalian cell culture production of commercial biologics. The site produces drugs including Dupixent (in partnership with Regeneron) and insulin products.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "Large-scale CHO bioreactors\nInsulin fermentation\nDownstream processing\nFill-finish",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "Formerly Genzyme Framingham site prior to Sanofi acquisition.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 2012,
        "Facility": "Novo Nordisk Durham",
        "Membership tier": "",
        "City": "Durham",
        "Country": "United States",
        "Address": "3612 Westchase Drive, Durham, NC 27703",
        "Contact person": "",
        "Website": "https://www.novonordisk-us.com",
        "Social links": "",
        "About": "Novo Nordisk's Durham facility is a large-scale mammalian cell culture manufacturing site producing commercial biologics. Following acquisition of Catalent Bloomington, Novo Nordisk expanded US manufacturing footprint to meet growing demand for GLP-1 drugs such as Ozempic and Wegovy.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "Fed-batch CHO bioreactors\nDownstream purification\nFill-finish",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 2013,
        "Facility": "Eli Lilly Indianapolis",
        "Membership tier": "",
        "City": "Indianapolis",
        "Country": "United States",
        "Address": "Lilly Corporate Center, Indianapolis, IN 46285",
        "Contact person": "",
        "Website": "https://www.lilly.com",
        "Social links": "",
        "About": "Eli Lilly's Indianapolis headquarters includes extensive biomanufacturing infrastructure for insulin, antibody, and peptide production. The site produces commercial biologics including Humalog insulin and novel GLP-1 receptor agonists (Mounjaro/tirzepatide).",
        "Technology areas": "Mammalian cell culture\nMicrobial fermentation",
        "Technologies": "E. coli fermentation (insulin)\nCHO cell culture\nDownstream processing\nFill-finish",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "Lilly investing >$9 billion in new US manufacturing for GLP-1 drugs as of 2023-2024.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 2014,
        "Facility": "Merck & Co. West Point",
        "Membership tier": "",
        "City": "West Point",
        "Country": "United States",
        "Address": "351 N Sumneytown Pike, North Wales, PA 19454",
        "Contact person": "",
        "Website": "https://www.merck.com",
        "Social links": "",
        "About": "Merck's West Point campus is the company's largest US manufacturing site and global headquarters for vaccine and biologic production. The site produces multiple vaccines including Gardasil, Varivax, M-M-R II, and Pneumovax, as well as biologics such as Keytruda.",
        "Technology areas": "Mammalian cell culture\nMicrobial fermentation",
        "Technologies": "Large-scale cell culture bioreactors\nVaccine fermentation\nDownstream processing\nFill-finish",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "One of the largest pharmaceutical manufacturing campuses in North America.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 2015,
        "Facility": "AstraZeneca Gaithersburg",
        "Membership tier": "",
        "City": "Gaithersburg",
        "Country": "United States",
        "Address": "One MedImmune Way, Gaithersburg, MD 20878",
        "Contact person": "",
        "Website": "https://www.astrazeneca.com",
        "Social links": "",
        "About": "AstraZeneca's Gaithersburg site (formerly MedImmune) is a key biologics manufacturing and R&D campus. The site produces commercial vaccines and monoclonal antibodies including Synagis and Bevespi, and houses significant biologic drug development capabilities.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "CHO cell culture\nMDCK cell culture (influenza)\nDownstream purification\nFill-finish",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "Former MedImmune HQ; acquired by AstraZeneca in 2007.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 2016,
        "Facility": "CSL Behring Kankakee",
        "Membership tier": "",
        "City": "Kankakee",
        "Country": "United States",
        "Address": "1020 West South Street, Kankakee, IL 60901",
        "Contact person": "",
        "Website": "https://www.cslbehring.com",
        "Social links": "",
        "About": "CSL Behring's Kankakee facility is a major US plasma protein fractionation and purification plant producing clotting factors, immunoglobulins (IVIG), albumin, and other plasma-derived therapeutics.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "Plasma fractionation\nChromatographic purification\nVirus inactivation\nFill-finish",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "Processes millions of litres of human plasma per year.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 2017,
        "Facility": "Grifols Los Angeles",
        "Membership tier": "",
        "City": "Los Angeles",
        "Country": "United States",
        "Address": "5555 Valley Blvd, Los Angeles, CA 90032",
        "Contact person": "",
        "Website": "https://www.grifols.com",
        "Social links": "",
        "About": "Grifols' Los Angeles facility (formerly Alpha Therapeutic) is a plasma fractionation plant producing albumin, IVIG, alpha-1 antitrypsin, and clotting factors. It is one of the company's key US manufacturing sites for plasma-derived therapies.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "Plasma fractionation\nCohn fractionation\nChromatographic purification\nFill-finish",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "Grifols acquired the site through the Alpha Therapeutic acquisition in 2003.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 2018,
        "Facility": "Takeda Cambridge",
        "Membership tier": "",
        "City": "Cambridge",
        "Country": "United States",
        "Address": "610 Main Street, Cambridge, MA 02139",
        "Contact person": "",
        "Website": "https://www.takeda.com",
        "Social links": "",
        "About": "Takeda's Cambridge site houses biologic drug development and early-stage manufacturing capabilities, focusing on oncology and rare disease programs. The site is a hub for cell therapy and plasma-derived biologics development.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "Cell therapy manufacturing\nProtein purification\nPlasmid DNA production",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "Formerly Shire Pharmaceuticals; acquired by Takeda in 2019.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 2019,
        "Facility": "Bayer Biologicals Berkeley",
        "Membership tier": "",
        "City": "Berkeley",
        "Country": "United States",
        "Address": "800 Dwight Way, Berkeley, CA 94710",
        "Contact person": "",
        "Website": "https://www.bayer.com",
        "Social links": "",
        "About": "Bayer's Berkeley biologicals site (formerly Miles Laboratories, then Cutter Biologicals) is one of the oldest US biologics manufacturing sites, producing plasma-derived clotting factors and recombinant hemophilia treatments including Kogenate.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "BHK cell culture (Factor VIII)\nPlasma fractionation\nDownstream purification",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "Historic site; in operation since 1960s for plasma biologics.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 2020,
        "Facility": "Gilead Sciences Foster City",
        "Membership tier": "",
        "City": "Foster City",
        "Country": "United States",
        "Address": "333 Lakeside Drive, Foster City, CA 94404",
        "Contact person": "",
        "Website": "https://www.gilead.com",
        "Social links": "",
        "About": "Gilead Sciences' Foster City headquarters includes pharmaceutical and biologic manufacturing capabilities for antiviral and oncology products. The site manufactures CAR-T cell therapies (Yescarta and Tecartus) for commercial distribution.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "CAR-T cell manufacturing\nLentiviral vector production\nCell therapy processing",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "Kite Pharma (Gilead subsidiary) primary CAR-T manufacturing hub.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    # ── Canadian facilities ──────────────────────────────────────────────────
    {
        "ID": 3001,
        "Facility": "Resilience Mississauga",
        "Membership tier": "",
        "City": "Mississauga",
        "Country": "Canada",
        "Address": "2585 Meadowpine Blvd, Mississauga, ON L5N 8H9",
        "Contact person": "",
        "Website": "https://www.resilience.com",
        "Social links": "",
        "About": "Resilience's Mississauga facility is a Canadian biologics manufacturing site providing CDMO services for mammalian cell culture and fill-finish operations. The site serves clinical and commercial stage customers.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "CHO cell culture\nFill-finish\nDownstream purification",
        "No. of technologies": 3,
        "Certifications": "Health Canada approved\nFDA approved\nGMP",
        "Non-technical services": "Tech transfer\nRegulatory support",
        "Open 24/7": "Yes",
        "Extra information": "Acquired from Therapure Biopharma.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 3002,
        "Facility": "Sanofi Connaught Campus",
        "Membership tier": "",
        "City": "Toronto",
        "Country": "Canada",
        "Address": "1755 Steeles Avenue West, Toronto, ON M2R 3T4",
        "Contact person": "",
        "Website": "https://www.sanofi.com",
        "Social links": "",
        "About": "Sanofi's Toronto Connaught campus is a historic Canadian vaccine and biologics manufacturing site, producing influenza vaccines, diphtheria-tetanus-pertussis vaccines, and other biologic products. The site was built on the legacy of Connaught Laboratories, one of the world's oldest vaccine manufacturers.",
        "Technology areas": "Mammalian cell culture\nMicrobial fermentation",
        "Technologies": "Egg-based influenza vaccine production\nBacterial vaccine fermentation\nFill-finish",
        "No. of technologies": 3,
        "Certifications": "Health Canada approved\nFDA approved\nEMA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "Connaught Laboratories founded in 1914; acquired by Sanofi (via Pasteur Mérieux) in 1989.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 3003,
        "Facility": "Precision BioSciences Durham",
        "Membership tier": "",
        "City": "Durham",
        "Country": "United States",
        "Address": "302 East Pettigrew Street, Durham, NC 27701",
        "Contact person": "",
        "Website": "https://www.precisionbiosciences.com",
        "Social links": "",
        "About": "Precision BioSciences is a genome editing company operating pilot and clinical manufacturing for allogeneic CAR-T cell therapies and in vivo gene editing products. Their Durham facility uses ARCUS nuclease technology for cell and gene therapy manufacturing.",
        "Technology areas": "Viral vector\nMammalian cell culture",
        "Technologies": "Lentiviral vector production\nT-cell expansion and engineering\nCAR-T manufacturing",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 3004,
        "Facility": "Ology Biosciences Frederick",
        "Membership tier": "",
        "City": "Frederick",
        "Country": "United States",
        "Address": "8440 Jefferson Davis Hwy, Frederick, MD 21701",
        "Contact person": "",
        "Website": "https://www.ologybio.com",
        "Social links": "",
        "About": "Ology Biosciences (formerly Emergent BioSolutions BARDA partner) in Frederick, Maryland operates a government-oriented biologics manufacturing facility specialising in vaccines, anthrax countermeasures, and emerging infectious disease preparedness.",
        "Technology areas": "Mammalian cell culture\nMicrobial fermentation",
        "Technologies": "Vaccine manufacturing\nFermentation-based antigen production\nFill-finish",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "Government contract manufacturing (BARDA)",
        "Open 24/7": "Yes",
        "Extra information": "",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    # ── Industrial biotech / fermentation ────────────────────────────────────
    {
        "ID": 4001,
        "Facility": "LanzaTech Skokie",
        "Membership tier": "",
        "City": "Skokie",
        "Country": "United States",
        "Address": "8045 Lamon Avenue, Skokie, IL 60077",
        "Contact person": "",
        "Website": "https://www.lanzatech.com",
        "Social links": "",
        "About": "LanzaTech develops gas fermentation technology to convert industrial waste gases (CO, CO2) into ethanol and other chemicals. The Skokie headquarters hosts R&D and pilot-scale fermentation reactors. LanzaTech's proprietary microorganism (Clostridium autoethanogenum) is the basis of its commercial gas fermentation process.",
        "Technology areas": "Fermentation (industrial)",
        "Technologies": "Gas fermentation\nCO/CO2 fermentation\nBioethanol production",
        "No. of technologies": 3,
        "Certifications": "",
        "Non-technical services": "Technology licensing\nProcess engineering",
        "Open 24/7": "Yes",
        "Extra information": "Commercial plants operating in partnership with ArcelorMittal (Belgium) and others; Skokie is the technology development hub.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 4002,
        "Facility": "Ginkgo Bioworks Boston",
        "Membership tier": "",
        "City": "Boston",
        "Country": "United States",
        "Address": "27 Drydock Avenue, Boston, MA 02210",
        "Contact person": "",
        "Website": "https://www.ginkgobioworks.com",
        "Social links": "",
        "About": "Ginkgo Bioworks operates a large automated foundry for cell program design and fermentation scale-up. Their Boston facility uses synthetic biology and high-throughput automation to develop and optimise microbial and mammalian cell culture processes for industrial and pharmaceutical customers.",
        "Technology areas": "Microbial fermentation\nMammalian cell culture",
        "Technologies": "High-throughput microbial fermentation\nSynthetic biology platform\nYeast fermentation\nE. coli fermentation",
        "No. of technologies": 4,
        "Certifications": "",
        "Non-technical services": "Strain engineering\nProcess development\nTechnology licensing",
        "Open 24/7": "Yes",
        "Extra information": "Went public via SPAC in 2021; operates 'Foundry' model for cell program development.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 4003,
        "Facility": "NREL Integrated Biorefinery",
        "Membership tier": "",
        "City": "Golden",
        "Country": "United States",
        "Address": "15013 Denver West Pkwy, Golden, CO 80401",
        "Contact person": "",
        "Website": "https://www.nrel.gov",
        "Social links": "",
        "About": "The National Renewable Energy Laboratory's Integrated Biorefinery Research Facility (IBRF) in Golden, Colorado provides pilot- and demonstration-scale fermentation and biorefinery process development. The facility supports development of cellulosic ethanol, biofuels, and bio-based chemicals from lignocellulosic feedstocks.",
        "Technology areas": "Fermentation (industrial)\nThermochemical",
        "Technologies": "Cellulosic ethanol fermentation\nPre-treatment (dilute acid, steam explosion)\nSimultaneous saccharification and fermentation (SSF)\nCatalytic upgrading",
        "No. of technologies": 4,
        "Certifications": "",
        "Non-technical services": "R&D collaboration\nProcess scale-up\nTechnology transfer",
        "Open 24/7": "No",
        "Extra information": "DOE national laboratory; open access for collaborative R&D with industry.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 4004,
        "Facility": "Joint BioEnergy Institute (JBEI)",
        "Membership tier": "",
        "City": "Emeryville",
        "Country": "United States",
        "Address": "5885 Hollis Street, Emeryville, CA 94608",
        "Contact person": "",
        "Website": "https://www.jbei.org",
        "Social links": "",
        "About": "The Joint BioEnergy Institute (JBEI) is a DOE Bioenergy Research Center operated by Lawrence Berkeley National Laboratory. The Emeryville facility houses pilot-scale fermentation, synthetic biology, and biomass deconstruction research for advanced biofuels and bio-based chemicals.",
        "Technology areas": "Fermentation (industrial)\nMicrobial fermentation",
        "Technologies": "Microbial fermentation (biofuels)\nBiomass pre-treatment\nSynthetic biology\nMetabolic engineering",
        "No. of technologies": 4,
        "Certifications": "",
        "Non-technical services": "Research collaboration\nTechnology transfer",
        "Open 24/7": "No",
        "Extra information": "DOE-funded research institute; established 2007.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 4005,
        "Facility": "BioMADE Ames",
        "Membership tier": "",
        "City": "Ames",
        "Country": "United States",
        "Address": "1805 Collaboration Place, Ames, IA 50010",
        "Contact person": "",
        "Website": "https://www.biomadesociety.org",
        "Social links": "",
        "About": "BioMADE (Bioindustrial Manufacturing and Design Ecosystem) is a DOD-funded Manufacturing Innovation Institute. The Ames facility focuses on scale-up of industrial biomanufacturing from pilot to demonstration scale, supporting the bioeconomy through shared infrastructure and tech transition for fermentation-based chemicals, materials, and biologics.",
        "Technology areas": "Fermentation (industrial)\nMicrobial fermentation",
        "Technologies": "Pilot-scale fermentation (up to 1,500 L)\nDownstream processing\nBioprocess analytics",
        "No. of technologies": 3,
        "Certifications": "",
        "Non-technical services": "Technology transition support\nMember services\nWorkforce development",
        "Open 24/7": "No",
        "Extra information": "DOD Manufacturing USA institute; established 2020 with $87M initial award.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 4006,
        "Facility": "Genomatica San Diego",
        "Membership tier": "",
        "City": "San Diego",
        "Country": "United States",
        "Address": "10520 Wateridge Circle, San Diego, CA 92121",
        "Contact person": "",
        "Website": "https://www.genomatica.com",
        "Social links": "",
        "About": "Genomatica develops bio-based processes for chemicals manufacturing, using engineered microorganisms. Their San Diego R&D campus houses fermentation pilot facilities for bio-butanediol (bio-BDO), bio-nylon intermediates, and other bio-based chemicals. Commercial production is licensed to partners.",
        "Technology areas": "Fermentation (industrial)\nMicrobial fermentation",
        "Technologies": "Metabolic engineering\nE. coli fermentation\nYeast fermentation\nDownstream separation",
        "No. of technologies": 4,
        "Certifications": "",
        "Non-technical services": "Technology licensing\nProcess development",
        "Open 24/7": "No",
        "Extra information": "Commercial bio-BDO production at Novamont (Italy) and BASF (Germany) under license.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 4007,
        "Facility": "Novozymes Blair",
        "Membership tier": "",
        "City": "Blair",
        "Country": "United States",
        "Address": "3300 Cornhusker Rd, Blair, NE 68008",
        "Contact person": "",
        "Website": "https://www.novozymes.com",
        "Social links": "",
        "About": "Novozymes' Blair, Nebraska facility is one of the company's largest fermentation production sites for industrial enzymes. The site produces microbially fermented enzymes for ethanol, biofuels, food & beverage, and cleaning applications at industrial scale.",
        "Technology areas": "Fermentation (industrial)\nMicrobial fermentation\nEnzymes",
        "Technologies": "Aspergillus fermentation\nBacillus fermentation\nEnzyme extraction and purification",
        "No. of technologies": 3,
        "Certifications": "ISO 9001\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "Major US hub for Novozymes' industrial enzyme business.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 4008,
        "Facility": "DSM-Firmenich Belvidere",
        "Membership tier": "",
        "City": "Belvidere",
        "Country": "United States",
        "Address": "45 Horseneck Road, Belvidere, NJ 07823",
        "Contact person": "",
        "Website": "https://www.dsm-firmenich.com",
        "Social links": "",
        "About": "DSM-Firmenich's Belvidere site is a large-scale fermentation and chemical synthesis facility producing vitamins (including B12), nutritional ingredients, and specialty chemicals via microbial fermentation. The site uses proprietary Pseudomonas and other microbial platforms.",
        "Technology areas": "Fermentation (industrial)\nMicrobial fermentation\nEnzymes",
        "Technologies": "Vitamin B12 fermentation\nNutritional ingredient fermentation\nDownstream extraction",
        "No. of technologies": 3,
        "Certifications": "FDA GRAS\nISO 9001\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "One of the world's largest vitamin B12 production sites.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    # ── Pilot / R&D facilities ───────────────────────────────────────────────
    {
        "ID": 5001,
        "Facility": "NIIMBL University of Delaware",
        "Membership tier": "",
        "City": "Newark",
        "Country": "United States",
        "Address": "590 Avenue 1743, Newark, DE 19713",
        "Contact person": "",
        "Website": "https://www.niimbl.us",
        "Social links": "",
        "About": "The National Institute for Innovation in Manufacturing Biopharmaceuticals (NIIMBL) is a Manufacturing USA institute headquartered at the University of Delaware. NIIMBL connects industry, academia, and government to accelerate US biopharmaceutical manufacturing innovation, including shared pilot-scale facilities and workforce development programs.",
        "Technology areas": "Mammalian cell culture\nMicrobial fermentation",
        "Technologies": "Pilot bioreactors\nContinuous manufacturing\nProcess analytical technology (PAT)",
        "No. of technologies": 3,
        "Certifications": "",
        "Non-technical services": "R&D collaboration\nWorkforce development\nTechnology roadmapping",
        "Open 24/7": "No",
        "Extra information": "DOC Manufacturing USA institute; $70M federal funding since 2017.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 5002,
        "Facility": "MIT Koch Institute Pilot Plant",
        "Membership tier": "",
        "City": "Cambridge",
        "Country": "United States",
        "Address": "500 Main Street, Cambridge, MA 02139",
        "Contact person": "",
        "Website": "https://ki.mit.edu",
        "Social links": "",
        "About": "MIT's Koch Institute for Integrative Cancer Research operates pilot-scale biomanufacturing facilities for cell therapy, mRNA, and nanoparticle drug delivery systems. The institute bridges academic research and clinical manufacturing with cGMP-compatible pilot suites.",
        "Technology areas": "Mammalian cell culture\nmRNA\nLipid nanoparticle",
        "Technologies": "mRNA synthesis\nLNP formulation\nCell therapy manufacturing\nAnalytical characterisation",
        "No. of technologies": 4,
        "Certifications": "GMP-compatible",
        "Non-technical services": "Academic collaboration\nTech transfer",
        "Open 24/7": "No",
        "Extra information": "",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 5003,
        "Facility": "BTEC North Carolina State University",
        "Membership tier": "",
        "City": "Raleigh",
        "Country": "United States",
        "Address": "850 Oval Drive, Raleigh, NC 27695",
        "Contact person": "",
        "Website": "https://btec.ncsu.edu",
        "Social links": "",
        "About": "The Biomanufacturing Training and Education Center (BTEC) at NC State University is a world-class facility for biomanufacturing training, pilot-scale process development, and technology scale-up. The facility operates cGMP-compatible mammalian and microbial manufacturing suites for academic and industry partners.",
        "Technology areas": "Mammalian cell culture\nMicrobial fermentation",
        "Technologies": "Pilot-scale bioreactors (up to 500 L)\nDownstream processing\nProcess analytics (PAT)",
        "No. of technologies": 3,
        "Certifications": "GMP-compatible",
        "Non-technical services": "Workforce training\nProcess development services\nCo-manufacturing",
        "Open 24/7": "No",
        "Extra information": "One of the premier biomanufacturing education and pilot facilities in the US.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 5004,
        "Facility": "Center for Breakthrough Medicines King of Prussia",
        "Membership tier": "",
        "City": "King of Prussia",
        "Country": "United States",
        "Address": "1100 First Avenue, King of Prussia, PA 19406",
        "Contact person": "",
        "Website": "https://www.thecenterforbm.com",
        "Social links": "",
        "About": "The Center for Breakthrough Medicines (CBM) is one of the world's largest cell and gene therapy CDMOs. The King of Prussia campus provides integrated viral vector, cell therapy, and plasmid DNA manufacturing services, supporting clinical and commercial programs.",
        "Technology areas": "Viral vector\nMammalian cell culture",
        "Technologies": "AAV manufacturing\nLentiviral vector production\nPlasmid DNA manufacturing\nCAR-T cell manufacturing\nFill-finish",
        "No. of technologies": 5,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "Process development\nAnalytical services\nRegulatory support",
        "Open 24/7": "Yes",
        "Extra information": "800,000+ sq ft campus; among the largest gene therapy CDMOs globally.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 5005,
        "Facility": "Forge Biologics Columbus",
        "Membership tier": "",
        "City": "Columbus",
        "Country": "United States",
        "Address": "6600 Rickenbacker Road, Columbus, OH 43217",
        "Contact person": "",
        "Website": "https://www.forgebiologics.com",
        "Social links": "",
        "About": "Forge Biologics is a gene therapy CDMO focused exclusively on AAV manufacturing for rare disease and other gene therapy programs. The Columbus facility ('The Hearth') provides clinical and commercial-scale AAV production.",
        "Technology areas": "Viral vector",
        "Technologies": "AAV manufacturing (multiple serotypes)\nBaculovirus/Sf9 production\nDownstream purification\nFill-finish",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "Process development\nAnalytical services\nRegulatory strategy",
        "Open 24/7": "Yes",
        "Extra information": "Founded 2020; raised over $100M Series B.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 5006,
        "Facility": "Andelyn Biosciences Columbus",
        "Membership tier": "",
        "City": "Columbus",
        "Country": "United States",
        "Address": "575 Children's Crossroads, Columbus, OH 43205",
        "Contact person": "",
        "Website": "https://www.andelynbiosciences.com",
        "Social links": "",
        "About": "Andelyn Biosciences (formerly Nationwide Children's Hospital gene therapy CDMO) is a leading viral vector CDMO with deep expertise in AAV manufacturing for rare and inherited disease gene therapies. The Columbus facility provides GMP-grade viral vector production.",
        "Technology areas": "Viral vector",
        "Technologies": "AAV manufacturing\nLentiviral vector\nRetroviral vector\nPlasmid DNA",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "Process development\nAnalytical development\nIPF (Investigational Product Facility) services",
        "Open 24/7": "Yes",
        "Extra information": "Spun out of Nationwide Children's Hospital Research Institute in 2021.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    # ── Closed / historical sites ────────────────────────────────────────────
    {
        "ID": 6001,
        "Facility": "Wyeth Pearl River (closed)",
        "Membership tier": "",
        "City": "Pearl River",
        "Country": "United States",
        "Address": "401 N Middletown Road, Pearl River, NY 10965",
        "Contact person": "",
        "Website": "",
        "Social links": "",
        "About": "Wyeth's Pearl River facility was one of the most historic US biologics manufacturing sites, producing vaccines (Prevnar, meningococcal) and biologic drugs via mammalian cell culture. Following Pfizer's acquisition of Wyeth in 2009, the Pearl River site was restructured with parts closed and others integrated into the Pfizer network.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "CHO cell culture\nVaccine fermentation\nFill-finish",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "No",
        "Extra information": "Status: Partially closed after Pfizer acquisition 2009; some operations transferred to Pfizer sites. Wyeth founded 1926.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 6002,
        "Facility": "Immunex Seattle (closed)",
        "Membership tier": "",
        "City": "Seattle",
        "Country": "United States",
        "Address": "51 University Street, Seattle, WA 98101",
        "Contact person": "",
        "Website": "",
        "Social links": "",
        "About": "Immunex Corporation was a pioneer US biotechnology company that developed Enbrel (etanercept) for rheumatoid arthritis. Immunex's Seattle manufacturing site produced Enbrel via CHO mammalian cell culture before the company was acquired by Amgen in 2002. The Seattle R&D and manufacturing operations were subsequently consolidated into Amgen's network.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "CHO cell culture\nProtein purification",
        "No. of technologies": 2,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "No",
        "Extra information": "Status: Closed; acquired by Amgen in 2002 for $16B. Manufacturing moved to Amgen West Greenwich RI.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 6003,
        "Facility": "Biogen Hilliard (closed)",
        "Membership tier": "",
        "City": "Hilliard",
        "Country": "United States",
        "Address": "5000 Hilliard Rome Road, Hilliard, OH 43026",
        "Contact person": "",
        "Website": "",
        "Social links": "",
        "About": "Biogen's Hilliard, Ohio biomanufacturing facility was built in the early 2000s as additional capacity for interferon beta production (Avonex). The site was decommissioned and sold as Biogen restructured its manufacturing network and consolidated production.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "CHO cell culture\nDownstream purification",
        "No. of technologies": 2,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "No",
        "Extra information": "Status: Closed; sold ~2015. Site now used for other purposes.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 6004,
        "Facility": "Diosynth RTP (closed / acquired)",
        "Membership tier": "",
        "City": "Research Triangle Park",
        "Country": "United States",
        "Address": "6051 George Watts Hill Drive, Research Triangle Park, NC 27709",
        "Contact person": "",
        "Website": "",
        "Social links": "",
        "About": "Diosynth Biotechnologies RTP was an early CDMO offering microbial and mammalian manufacturing services. Diosynth (formerly Akzo Nobel Diosynth) was acquired by SAFC (Sigma-Aldrich) and subsequently by Fujifilm in 2011 to form Fujifilm Diosynth Biotechnologies. The RTP site continued operating under Fujifilm ownership.",
        "Technology areas": "Mammalian cell culture\nMicrobial fermentation",
        "Technologies": "E. coli fermentation\nCHO cell culture\nProtein purification",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "No",
        "Extra information": "Status: Acquired and rebranded as Fujifilm Diosynth Biotechnologies RTP (see entry 1004).",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 6005,
        "Facility": "Genzyme Allston (closed)",
        "Membership tier": "",
        "City": "Allston",
        "Country": "United States",
        "Address": "500 Soldiers Field Road, Allston, MA 02134",
        "Contact person": "",
        "Website": "",
        "Social links": "",
        "About": "Genzyme's Allston facility was the primary manufacturing site for the rare disease enzyme replacement therapies including Cerezyme (imiglucerase) for Gaucher disease. A 2009 contamination incident caused a global shortage and patient crisis. The site was subsequently modernised. Sanofi acquired Genzyme in 2011.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "CHO cell culture\nEnzyme production\nDownstream purification",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "No",
        "Extra information": "Status: Closed post-Sanofi acquisition; manufacturing consolidated to other Sanofi/Genzyme sites. The 2009 Allston Vesivirus contamination is a landmark case study in biomanufacturing risk.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 6006,
        "Facility": "Amgen Seattle (closed)",
        "Membership tier": "",
        "City": "Seattle",
        "Country": "United States",
        "Address": "1201 Amgen Court West, Seattle, WA 98119",
        "Contact person": "",
        "Website": "",
        "Social links": "",
        "About": "Amgen operated a manufacturing and R&D site in Seattle following its acquisition of Immunex in 2002. This site (formerly Immunex) was gradually consolidated as Amgen centralised biologics production to its West Greenwich and Thousand Oaks sites. The Seattle facility was primarily R&D-focused in its later years.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "CHO cell culture\nBioreactor operations\nDownstream processing",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "No",
        "Extra information": "Status: Closed; Amgen Seattle R&D retained but manufacturing consolidated. Site vacated ~2018.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 6007,
        "Facility": "Covance Biologics Mooresville (closed)",
        "Membership tier": "",
        "City": "Mooresville",
        "Country": "United States",
        "Address": "8211 SciCor Drive, Mooresville, NC 28117",
        "Contact person": "",
        "Website": "",
        "Social links": "",
        "About": "Covance Biologics operated a mammalian cell culture CDMO site in Mooresville, NC focused on clinical-stage biologics manufacturing. The site was closed following LabCorp's acquisition of Covance in 2015 and subsequent restructuring. Previously served clinical development customers with GMP mAb production.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "CHO cell culture\nClinical biomanufacturing\nDownstream processing",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "No",
        "Extra information": "Status: Closed ~2016 after LabCorp acquisition of Covance.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 6008,
        "Facility": "Albany Molecular Research (AMRI) Albany (closed)",
        "Membership tier": "",
        "City": "Albany",
        "Country": "United States",
        "Address": "21 Corporate Circle, Albany, NY 12203",
        "Contact person": "",
        "Website": "",
        "Social links": "",
        "About": "Albany Molecular Research Inc (AMRI) operated CRO/CDMO services from its Albany headquarters with biologics capabilities. AMRI was acquired by Bridgepoint in 2017 and subsequently split into multiple entities. The biologics manufacturing assets were absorbed or closed.",
        "Technology areas": "Mammalian cell culture\nMicrobial fermentation",
        "Technologies": "E. coli fermentation\nCHO cell culture\nProtein purification",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "No",
        "Extra information": "Status: Company split after Bridgepoint acquisition 2017; Albany biologics operations closed.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    # ── Additional CDMOs / specialty ─────────────────────────────────────────
    {
        "ID": 1016,
        "Facility": "Charles River Biologics Bloomington",
        "Membership tier": "",
        "City": "Bloomington",
        "Country": "United States",
        "Address": "5700 W 84th Street, Bloomington, MN 55437",
        "Contact person": "",
        "Website": "https://www.crl.com",
        "Social links": "",
        "About": "Charles River Laboratories offers biologics testing, cell banking, and early-phase CDMO services at multiple US sites. Their biologics operations support cell line characterisation, master/working cell bank production, and viral safety testing for pharmaceutical clients.",
        "Technology areas": "Mammalian cell culture\nMicrobial fermentation",
        "Technologies": "Cell line development\nMaster cell banking\nViral safety testing",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "Regulatory consulting\nBiologics testing",
        "Open 24/7": "Yes",
        "Extra information": "",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 1017,
        "Facility": "Phibro Animal Health Teaneck",
        "Membership tier": "",
        "City": "Teaneck",
        "Country": "United States",
        "Address": "Glenpointe Centre East, 300 Frank W Burr Blvd, Teaneck, NJ 07666",
        "Contact person": "",
        "Website": "https://www.pahc.com",
        "Social links": "",
        "About": "Phibro Animal Health manufactures vaccines and biologics for animal health applications. US sites produce fermentation-based veterinary vaccines and pharmaceutical products using both mammalian cell culture and microbial fermentation.",
        "Technology areas": "Mammalian cell culture\nMicrobial fermentation",
        "Technologies": "Veterinary vaccine production\nBacterial fermentation\nViral vaccine manufacturing",
        "No. of technologies": 3,
        "Certifications": "USDA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 1018,
        "Facility": "Patheon/Thermo Fisher Biologics Brisbane",
        "Membership tier": "",
        "City": "Brisbane",
        "Country": "United States",
        "Address": "4560 Horton Street, Emeryville, CA 94608",
        "Contact person": "",
        "Website": "https://www.thermofisher.com/patheon",
        "Social links": "",
        "About": "Thermo Fisher Scientific (via Patheon acquisition) operates biologics CDMO services from multiple North American sites. The Emeryville, CA site offers mammalian cell culture process development and clinical manufacturing for biopharmaceutical customers.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "CHO cell culture\nSingle-use bioreactors\nDownstream processing\nFill-finish",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "Cell line development\nProcess development\nFormulation",
        "Open 24/7": "Yes",
        "Extra information": "Patheon acquired by Thermo Fisher for $7.2B in 2017.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 1019,
        "Facility": "Samsung Biologics America San Francisco",
        "Membership tier": "",
        "City": "San Francisco",
        "Country": "United States",
        "Address": "1 Market Street, San Francisco, CA 94105",
        "Contact person": "",
        "Website": "https://www.samsungbiologics.com",
        "Social links": "",
        "About": "Samsung Biologics maintains a North American presence through its San Francisco business development office and CDO (Contract Development Organization) services. While primary manufacturing is in Incheon, Korea, the company actively pursues US partnerships and has announced plans for US-based manufacturing.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "CHO cell culture (Korea-based)\nCDO services (US-based)",
        "No. of technologies": 2,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "Process development\nAnalytical development",
        "Open 24/7": "No",
        "Extra information": "Manufacturing primarily in Incheon, Korea; US office supports North American customers.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 1020,
        "Facility": "ElevateBio Waltham",
        "Membership tier": "",
        "City": "Waltham",
        "Country": "United States",
        "Address": "200 Second Avenue, Waltham, MA 02451",
        "Contact person": "",
        "Website": "https://www.elevatebio.com",
        "Social links": "",
        "About": "ElevateBio is a technology and manufacturing company for cell and gene therapies. Their Waltham, MA facility ('BaseCamp') provides integrated viral vector and cell therapy manufacturing capabilities, combining process development and GMP production for multiple gene therapy programs.",
        "Technology areas": "Viral vector\nMammalian cell culture",
        "Technologies": "AAV manufacturing\nLentiviral vector\nCAR-T cell manufacturing\nPlasmid DNA",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "Process development\nAnalytical services",
        "Open 24/7": "Yes",
        "Extra information": "Founded 2017; raised $850M+. BaseCamp is a 150,000 sq ft facility.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 1021,
        "Facility": "Vigene Biosciences Rockville",
        "Membership tier": "",
        "City": "Rockville",
        "Country": "United States",
        "Address": "9430 Key West Ave, Rockville, MD 20850",
        "Contact person": "",
        "Website": "https://www.vigene.com",
        "Social links": "",
        "About": "Vigene Biosciences is a viral vector CDMO providing AAV, lentivirus, adenovirus, and retrovirus manufacturing for gene therapy research and clinical programs. The Rockville facility offers both GMP and non-GMP viral vector production.",
        "Technology areas": "Viral vector",
        "Technologies": "AAV manufacturing\nLentiviral vector\nAdenoviral vector\nRetroviral vector",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "Process development\nAnalytical services",
        "Open 24/7": "Yes",
        "Extra information": "",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 1022,
        "Facility": "Waisman Biomanufacturing Madison",
        "Membership tier": "",
        "City": "Madison",
        "Country": "United States",
        "Address": "1500 Highland Avenue, Madison, WI 53705",
        "Contact person": "",
        "Website": "https://www.waismanbiomanufacturing.wisc.edu",
        "Social links": "",
        "About": "Waisman Biomanufacturing at the University of Wisconsin-Madison is an academic CDMO that provides GMP-grade manufacturing of biologics, cell therapies, and viral vectors for clinical trials. The facility supports early-phase IND-enabling manufacturing for academic and small biotech customers.",
        "Technology areas": "Mammalian cell culture\nViral vector",
        "Technologies": "CHO and HEK cell culture\nAAV manufacturing\nCell therapy processing\nDownstream purification",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "Process development\nIND support\nRegulatory assistance",
        "Open 24/7": "No",
        "Extra information": "Academic CDMO; focuses on under-resourced developers who cannot access commercial CDMOs.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 1023,
        "Facility": "Protein Design Labs (PDL) BioPharma Fremont (closed)",
        "Membership tier": "",
        "City": "Fremont",
        "Country": "United States",
        "Address": "34790 Ardenwood Blvd, Fremont, CA 94555",
        "Contact person": "",
        "Website": "",
        "Social links": "",
        "About": "Protein Design Labs was a pioneering antibody humanisation company that operated manufacturing and R&D at Fremont, CA. The company later became PDL BioPharma and focused on its patent royalty business rather than manufacturing. The Fremont R&D and pilot manufacturing facility was wound down.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "Antibody engineering\nCHO cell culture\nPilot biomanufacturing",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "No",
        "Extra information": "Status: Closed; PDL BioPharma dissolved in 2020.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 2021,
        "Facility": "AstraZeneca Frederick",
        "Membership tier": "",
        "City": "Frederick",
        "Country": "United States",
        "Address": "600 Clipper Drive, Belcamp, MD 21017",
        "Contact person": "",
        "Website": "https://www.astrazeneca.com",
        "Social links": "",
        "About": "AstraZeneca operates a biologics manufacturing facility at its Maryland campus that supports commercial production of respiratory and oncology biologics. The site was significantly involved in COVID-19 vaccine manufacturing (AZD1222) via subcontracting with Emergent BioSolutions.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "CHO cell culture\nDownstream processing\nFill-finish",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 3004,
        "Facility": "Sanofi Swiftwater",
        "Membership tier": "",
        "City": "Swiftwater",
        "Country": "United States",
        "Address": "Discovery Drive, Swiftwater, PA 18370",
        "Contact person": "",
        "Website": "https://www.sanofi.com",
        "Social links": "",
        "About": "Sanofi's Swiftwater facility is one of the world's largest influenza vaccine manufacturing sites, producing hundreds of millions of influenza vaccine doses annually via egg-based and cell-based processes. The site also manufactures rabies and other vaccines.",
        "Technology areas": "Mammalian cell culture\nMicrobial fermentation",
        "Technologies": "Egg-based influenza vaccine production\nCell-based influenza vaccine (MDCK)\nRabies vaccine production\nFill-finish",
        "No. of technologies": 4,
        "Certifications": "FDA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "Formerly Wyeth-Lederle (then Aventis Pasteur) site; one of the oldest US vaccine facilities in continuous operation.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 4009,
        "Facility": "Archer Daniels Midland Decatur",
        "Membership tier": "",
        "City": "Decatur",
        "Country": "United States",
        "Address": "4666 Faries Pkwy, Decatur, IL 62526",
        "Contact person": "",
        "Website": "https://www.adm.com",
        "Social links": "",
        "About": "ADM's Decatur campus includes large-scale wet mill corn processing and fermentation for ethanol, lysine, citric acid, sorbitol, and other bio-based chemicals. The site is one of the largest corn wet mills in North America and represents industrial-scale fermentation and bioproduction.",
        "Technology areas": "Fermentation (industrial)\nMicrobial fermentation",
        "Technologies": "Corn wet milling\nLysine fermentation\nCitric acid fermentation\nEthanol fermentation",
        "No. of technologies": 4,
        "Certifications": "ISO 9001\nFDA GRAS",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "One of the largest bioprocessing complexes in the world by volume.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 4010,
        "Facility": "Cargill Blair Fermentation",
        "Membership tier": "",
        "City": "Blair",
        "Country": "United States",
        "Address": "1502 Cornhusker Drive, Blair, NE 68008",
        "Contact person": "",
        "Website": "https://www.cargill.com",
        "Social links": "",
        "About": "Cargill operates large-scale fermentation facilities for food ingredients, amino acids, and industrial biochemicals at its Blair, NE site. The facility produces lysine and other amino acids via microbial fermentation for feed and food markets.",
        "Technology areas": "Fermentation (industrial)\nMicrobial fermentation",
        "Technologies": "Lysine fermentation\nCorn wet milling\nDownstream separation",
        "No. of technologies": 3,
        "Certifications": "ISO 9001\nFDA GRAS",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 5007,
        "Facility": "Sanofi Genzyme Waltham",
        "Membership tier": "",
        "City": "Waltham",
        "Country": "United States",
        "Address": "500 Kendall Street, Cambridge, MA 02142",
        "Contact person": "",
        "Website": "https://www.sanofi.com",
        "Social links": "",
        "About": "Sanofi's Genzyme campus in Cambridge/Waltham is a major biologics manufacturing and R&D hub producing rare disease enzyme replacement therapies including Cerezyme, Fabrazyme, Aldurazyme, and Myozyme. These complex lysosomal storage disease therapies are produced via mammalian cell culture.",
        "Technology areas": "Mammalian cell culture",
        "Technologies": "CHO cell culture\nEnzyme replacement therapy manufacturing\nDownstream purification",
        "No. of technologies": 3,
        "Certifications": "FDA approved\nEMA approved\nGMP",
        "Non-technical services": "",
        "Open 24/7": "Yes",
        "Extra information": "Formerly Genzyme Corp; acquired by Sanofi for $20.1B in 2011.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
    {
        "ID": 5008,
        "Facility": "Intrexon Germantown (closed)",
        "Membership tier": "",
        "City": "Germantown",
        "Country": "United States",
        "Address": "20374 Seneca Meadows Pkwy, Germantown, MD 20876",
        "Contact person": "",
        "Website": "",
        "Social links": "",
        "About": "Intrexon (now Precigen) operated synthetic biology and biomanufacturing facilities in Germantown, MD. The site hosted development of UltraVector synthetic biology platform and pilot-scale fermentation for engineered microorganisms producing biofuels, health products, and other bio-based chemicals.",
        "Technology areas": "Microbial fermentation\nMammalian cell culture",
        "Technologies": "Synthetic biology development\nMicrobial fermentation\nCell line engineering",
        "No. of technologies": 3,
        "Certifications": "",
        "Non-technical services": "",
        "Open 24/7": "No",
        "Extra information": "Status: Rebranded as Precigen; Germantown manufacturing activities reduced after business restructuring 2020.",
        "Downloads": "",
        "Videos": "",
        "Logo": "",
        "Pilots4U page": "",
    },
]


def create_excel(output_path: str):
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Facilities"

    headers = [
        "ID", "Facility", "Membership tier", "City", "Country",
        "Address", "Contact person", "Website", "Social links",
        "About", "Technology areas", "Technologies", "No. of technologies",
        "Certifications", "Non-technical services", "Open 24/7",
        "Extra information", "Downloads", "Videos", "Logo", "Pilots4U page",
    ]

    # Header row style
    header_fill = PatternFill("solid", fgColor="1F4E79")
    header_font = Font(bold=True, color="FFFFFF", size=11)
    for col, h in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col, value=h)
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(wrap_text=True, vertical="center")

    # Data rows
    for row_idx, f in enumerate(FACILITIES, 2):
        for col_idx, header in enumerate(headers, 1):
            ws.cell(row=row_idx, column=col_idx, value=f.get(header, ""))

    # Column widths
    widths = {
        "A": 6, "B": 40, "C": 14, "D": 20, "E": 14,
        "F": 30, "G": 20, "H": 35, "I": 20,
        "J": 60, "K": 30, "L": 40, "M": 8,
        "N": 30, "O": 25, "P": 8,
        "Q": 40, "R": 15, "S": 15, "T": 20, "U": 35,
    }
    for col, width in widths.items():
        ws.column_dimensions[col].width = width

    ws.row_dimensions[1].height = 30

    # Freeze header
    ws.freeze_panes = "A2"

    wb.save(output_path)
    print(f"Saved {len(FACILITIES)} facilities to {output_path}")


if __name__ == "__main__":
    out = Path(__file__).parent.parent / "data" / "NorthAmerica_database_1.xlsx"
    create_excel(str(out))
